#
# Config -----------------------------------------------------------------------
#

# Give the paths to the folder which contains the protocol template file 'path_MPS_Template'
# and the path where the created protocol files will be exported 'path_MPS_Biologic'

path_MPS_Template: 'C:\YourPathToTheTemplateFile'
path_MPS_Biologic: 'C:\YourPathForExportedProtocolFiles'

# Lines in the template file that will be replaced with sample info

mass_electrode_template : 'Mass of active material : 7000,000 mg'
capacity_cell_template : 'Battery capacity : 0,000 A.h'
current_limit_cp_step_template : 'Im                  0,000               150,000             0,000'

# Minimum and maximum value for the active material weight in an electrode in grams
cam_min_value: '0.0140'
cam_max_value: '0.0155'